//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdk0401_pr1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersInfo
    {
        public int ID { get; set; }
        public int IDPartnerType { get; set; }
        public int IDPartnerName { get; set; }
        public int IDDirectorName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string JurAddress { get; set; }
        public string INN { get; set; }
        public int Rate { get; set; }
    
        public virtual DirectorNames DirectorNames { get; set; }
        public virtual PartnerNames PartnerNames { get; set; }
        public virtual PartnerTypes PartnerTypes { get; set; }
    }
}
