//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdk0401_pr1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersProducts
    {
        public int ID { get; set; }
        public int IDProduct { get; set; }
        public int IDPartner { get; set; }
        public int ProductAmount { get; set; }
    
        public virtual PartnerNames PartnerNames { get; set; }
        public virtual Products Products { get; set; }
    }
}
